development:
  adapter: redis

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:d0ed635634356d4408c1effb00bc9493@hoki.redistogo.com:9247/
  channel_prefix: pixel_grid_production
