import "bootstrap";
import { initGrid } from '../modules/init_grid';
import { initStage } from '../modules/init_stage';
import { initTracker } from '../modules/init_tracker';
import { initClicker } from '../modules/init_clicker';
// import { initColsPicker } from '../modules/init_colspicker';
initGrid();
initStage();
initTracker();
initClicker();
// initColsPicker();
