class User < ApplicationRecord
  has_many :orders
  has_many :messages

  # Pre-generated by devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
