class User < ApplicationRecord
  has_many :placements
  has_many :orders

  # Pre-generated by devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
