class User < ApplicationRecord
  has_many :orders
  has_many :messages

  validates :username, presence: true

  # Pre-generated by devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
